### ISSUE TITLE
Local Storage Operator integration with IBM Cloud Satellite Storage

### ISSUE THREAD

**Issue by nkkashyap** [IBM/ibm-satellite-storage#17]
**Storage Solution Description**:
Local persistent volumes allow you to access local storage devices, such as a disk or partition, by using the standard persistent volume claim interface. Local Storage Operator enables local volumes in your cluster.
For further details about the storage solution refer to 
https://docs.openshift.com/container-platform/4.5/storage/persistent_storage/persistent-storage-local.html

**Comment by nkkashyap** [comment]
Resource specification files used for verification
**deployment.yaml**
```
---
apiVersion: v1
kind: List
metadata:
    name: local-volume
    namespace: kube-system
    annotations:
        version: local-volume-45
items:
    - apiVersion: v1
      kind: Namespace
      metadata:
          name: local-storage
    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
          name: local-operator-group
          namespace: local-storage
      spec:
          targetNamespaces:
              - local-storage
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
          name: local-storage-operator
          namespace: local-storage
      spec:
          channel: "4.5"
          installPlanApproval: Automatic
          name: local-storage-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
    - apiVersion: local.storage.openshift.io/v1
      kind: LocalVolume
      metadata:
          name: local-disk
          namespace: local-storage
      spec:
          nodeSelector:
              nodeSelectorTerms:
                  - matchExpressions:
                        - key: storage
                          operator: In
                          values:
                              - "localvol"
          storageClassDevices:
              - storageClassName: "localblock-sc"
                volumeMode: Block
                devicePaths:
                    - /dev/xvde
```

**localvol-pvc.yaml**
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localvol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Block
  storageClassName: localblock-sc
```
**localvol-pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: localvol-pod
spec:
  volumes:
  - name: localpvc
    persistentVolumeClaim:
        claimName: localvol-pvc
  containers:
  - name: devtest
    image: gcr.io/google-samples/node-hello:1.0
    volumeDevices:
    - name: localpvc
      devicePath: /dev/sda
```
