### ISSUE TITLE
IBM block storage CSI driver integration with IBM Cloud Satellite Storage

### ISSUE THREAD

**Issue by roysahar-ibm** [IBM/ibm-satellite-storage#26]
**IBM block storage CSI driver Description:**
IBM block storage CSI driver is leveraged by Kubernetes persistent volumes (PVs) to dynamically provision for block storage used with stateful containers.
IBM block storage CSI driver is based on an open-source IBM project (CSI driver), included as a part of IBM storage orchestration for containers. IBM storage orchestration for containers enables enterprises to implement a modern container-driven hybrid multicloud environment that can reduce IT costs and enhance business agility, while continuing to derive value from existing systems.
By leveraging CSI (Container Storage Interface) drivers for IBM storage systems, Kubernetes persistent volumes (PVs) can be dynamically provisioned for block or file storage to be used with stateful containers, such as database applications (IBM Db2®, MongoDB, PostgreSQL, etc) running in Red Hat® OpenShift® Container Platform and/or Kubernetes clusters. Storage provisioning can be fully automatized with additional support of cluster orchestration systems to automatically deploy, scale, and manage containerized applications.
For further details about the storage solution refer to - https://www.ibm.com/support/knowledgecenter/SSRQ8T_1.4.0/csi_block_storage_kc_welcome.html

**Comment by roysahar-ibm** [comment]
**deployment.yaml**
```
apiVersion: v1
kind: List
metadata:
  name: ibm-csi-block
  namespace: kube-system
  annotations:
    version: "template-v01"
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ibm-csi
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: operatorgroup
      namespace: ibm-csi
    spec:
      targetNamespaces:
      - ibm-csi
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ibm-block-csi-operator
      namespace: ibm-csi
      labels:
        app.kubernetes.io/name: ibm-block-csi-operator
        app.kubernetes.io/instance: ibm-block-csi-operator
        app.kubernetes.io/managed-by: ibm-block-csi-operator
        release: ibm-block-csi-operator
    spec:
      channel: stable
      name: ibm-block-csi-operator
      source: certified-operators
      sourceNamespace: openshift-marketplace
      startingCSV: ibm-block-csi-operator.v1.4.0
      installPlanApproval: Automatic
  - apiVersion: csi.ibm.com/v1
    kind: IBMBlockCSI
    metadata:
      labels:
        app.kubernetes.io/instance: ibm-block-csi-operator
        app.kubernetes.io/managed-by: ibm-block-csi-operator
        app.kubernetes.io/name: ibm-block-csi-operator
      name: ibm-block-csi
      namespace: ibm-csi
    spec:
      controller:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - s390x
                  - ppc64le
        imagePullPolicy: IfNotPresent
        repository: ibmcom/ibm-block-csi-driver-controller
        tag: 1.4.0
      node:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - s390x
                  - ppc64le
        imagePullPolicy: IfNotPresent
        repository: ibmcom/ibm-block-csi-driver-node
        tag: 1.4.0
      sidecars:
      - imagePullPolicy: IfNotPresent
        name: csi-node-driver-registrar
        repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
        tag: v2.0.1
      - imagePullPolicy: IfNotPresent
        name: csi-provisioner
        repository: k8s.gcr.io/sig-storage/csi-provisioner
        tag: v2.0.2
      - imagePullPolicy: IfNotPresent
        name: csi-attacher
        repository: k8s.gcr.io/sig-storage/csi-attacher
        tag: v3.0.0
      - imagePullPolicy: IfNotPresent
        name: csi-snapshotter
        repository: k8s.gcr.io/sig-storage/csi-snapshotter
        tag: v3.0.0
      - imagePullPolicy: IfNotPresent
        name: csi-resizer
        repository: k8s.gcr.io/sig-storage/csi-resizer
        tag: v1.0.0
      - imagePullPolicy: IfNotPresent
        name: livenessprobe
        repository: k8s.gcr.io/sig-storage/livenessprobe
        tag: v2.1.0
```

**pvc-test.yaml**
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
  namespace: mynamespace
spec:
  storageClassName: sc-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**mypod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: mynamespace
spec:
  containers:
  - name: myapp
    image: alpine
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: pvc-test
        mountPath: "/data"
  volumes:
     - name: pvc-test
       persistentVolumeClaim:
         claimName: pvc-test
  nodeSelector:
    kubernetes.io/hostname: 9.151.161.108
```
